name = "Nakiri-Electricity（替换成你的项目名称）"
main = "worker.js"
compatibility_date = "2025-12-09"

[site]
bucket = "./dist"

# --- D1 数据库 ---
[[d1_databases]]
binding = "DB"
database_name = "（这里填入数据库名称）"
database_id = "（如果你是手动创建的，这里填入你创建的数据库ID）"

# --- 定时任务 (Cron) ---
# 每小时执行一次
[triggers]
crons = ["0 * * * *"]

# --- 环境变量 ---
[vars]
ROOM_ID = "507"
PART_ID = "徐汇"
BUILD_ID = "18"