name = "nakiri-electricity"
main = "worker.js"
compatibility_date = "2025-12-09"

[site]
bucket = "./dist"

# --- D1 数据库 ---
[[d1_databases]]
binding = "DB"
database_name = "electric-db"
database_id = "f6d50a47-3174-4803-bea5-b0b18d9fc79f"

# --- 定时任务 (Cron) ---
# 每小时执行一次
[triggers]
crons = ["0 * * * *"]

# --- 环境变量 ---
[vars]
ROOM_ID = "507"
PART_ID = "徐汇"
BUILD_ID = "18"