name = "nakiri-electricity"
main = "worker.js"
compatibility_date = "2024-04-05"

[site]
bucket = "./dist"

# --- D1 数据库绑定 ---
[[d1_databases]]
binding = "DB"
database_name = "nakiri-db"
database_id = "f6d50a47-3174-4803-bea5-b0b18d9fc79f"

# --- 定时任务 (Cron) ---
# 每小时执行一次
[triggers]
crons = ["0 * * * *"]

# --- 环境变量 (本地开发用) ---
[vars]
ROOM_ID = "507"
PART_ID = "徐汇"
BUILD_ID = "18"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1